#!/usr/bin/env bash

#======================================================================================================
#title           :explore
#description     :Opens a specified file or directory given a path to it (Ubuntu XFCE-specific)
#author          :dharvey-consbio
#usage           :see https://github.com/consbio/cookbook/tree/master/bash/cmd-line-utilities/#explore
#======================================================================================================

if [[ ! -t 0 ]] ; then
  # Input from pipe or file (not terminal)
  export openfile="$(cat)"
else
  # Input from terminal (args)
  export openfile="$1"
fi

if [[ -z $openfile ]] ; then
  xdg-open ./
elif [[ -d $openfile ]]; then
  xdg-open "$openfile"
elif [[ -f $openfile ]]; then
  gedit "$openfile"
else
  echo "$openfile is not a file"
  exit 1
fi
