#!/usr/bin/env bash

#=======================================================================================================
#title           :howmuch
#description     :Lists sizes of all files in specified directory human readably, and sorted descending
#author          :dharvey-consbio
#usage           :see https://github.com/consbio/cookbook/tree/master/bash/cmd-line-utilities/#howmuch
#=======================================================================================================

export GLOBIGNORE=".:.."

if [[ ! -t 0 ]] ; then
  # Input from pipe or file (not terminal)
  export checkdir="$(cat)"
elif [[ -z $1 ]] ; then
  export checkdir=.
else
  export checkdir="$1"
fi

if [[ -d $checkdir ]]; then
  cd $checkdir
else
  echo "$checkdir is not a directory"
  exit 1
fi

if [[ -e ".*" ]] ; then
  du -chs .[!.]* * |sort -r --human-numeric-sort |head -11
else
  du -chs * |sort -r --human-numeric-sort |head -11
fi
