#!/bin/bash

#===============================================================================================
#title           :explore
#description     :Opens a specified file or directory given a path to it (Ubuntu XFCE-specific)
#author          :dharvey-consbio
#usage           :
#   # Search commands in history with text containing "search"
#   explore "filename"       # opens in notepadqq
#   explore "directoryname"  # opens in XFCE finder
#===============================================================================================

export openfile="$1"

if [[ -z $openfile ]] ; then
  xdg-open ./
elif [[ -d $openfile ]]; then
  xdg-open "$1"
elif [[ -f $openfile ]]; then
  notepadqq "$1"
else
  echo "$1 is not a file"
  exit 1
fi
