#!/bin/bash

#================================================================================================================
#title           :when
#description     :Executes case-insensitive file name searches of commands in history containing the search text
#author          :dharvey-consbio
#usage           :see https://github.com/consbio/cookbook/tree/master/bash/cmd-line-searches/#when
#=================================================================================================================

HISTFILE=~/.bash_history  # Set the history file
HISTTIMEFORMAT='%F %T '   # Set the hitory time format
set -o history            # Enable the history

if [[ ! -t 0 ]] ; then

  # Input from pipe or file (not terminal)
  export searchfor="$(cat)"

  if [[ -z $searchfor ]] ; then
    export searchfor="$*"
  fi

else

  # Input from terminal (args)
  export searchfor="$1"

fi



if [[ -z $searchfor ]] ; then
  echo "Printing full history"
  # cat ~/.bash_history
else
  echo "Searching history for \"$searchfor\""

  while read -r search;
  do
    history | grep -i --color "$search"
  done <<< "$searchfor"
fi
