#!/usr/bin/env bash

#==================================================================================================================
#title           :wherein
#description     :This script executes case-insensitive searches within files for lines containing the search text
#author          :dharvey-consbio
#usage           :see https://github.com/consbio/cookbook/tree/master/bash/cmd-line-searches/#wherein
#==================================================================================================================

if [[ ! -t 0 ]] ; then

  # Input from pipe or file (not terminal)
  export searchfor="$(cat)"
  export searchin=.

  if [[ -z $searchfor ]] ; then
    export searchfor="$*"
  fi

else

  # Input from terminal (args)
  export searchfor="$1"

  if [[ -z $2 ]] ; then
    export searchin=.
  else
    export searchin="$2"
  fi
fi

if [[ -z $searchfor ]] ; then
  echo 'Nothing to search for'
  exit 1
fi

while read -r search;
do
  echo "Searching for $search in $searchin"
  grep -rli --color "$search" "$searchin"
done <<< "$searchfor"
